### ISSUE TITLE
test factories first, after upgrade to 2.1.1

### ISSUE THREAD

**Issue by abatko** [blowmage/minitest-rails#172]
Before the upgrade I was able to do the following as per [this SO answer](http://stackoverflow.com/a/20277293):
```
MiniTest::Rails::Testing.default_tasks.unshift('aaa_factories_tests')
```

How can I test `factories` first?

Incidentally, how can I test `features` last?

**Comment by blowmage** [comment]
You will need to write your own rake tasks. See the README's [Running Tests](https://github.com/blowmage/minitest-rails/blob/master/README.rdoc#running-tests).

**Comment by metaskills** [comment]
There are some oddities with custom Rake tasks in Rails 4.1 and up. I found it was a bit tricky to get things to line up as I wanted. Even tho I do not use mintiest-rails, perhaps you might find this helpful. http://metaskills.net/2015/02/08/customizing-rake-tasks-in-rails-41-and-higher/

**Comment by blowmage** [comment]
## Adding new test directories

Rails 4.1 introduced spring as a mechanism to keep an instance of your rails app available for running tests against. Part of the reason `MiniTest::Rails::Testing.default_tasks` was removed in 2.0 is because of the complexities involved in supporting spring. The default rails testing tasks will always support spring and there is little benefit from duplicating this.

The other thing Rails 4.1 introduced is the ability to combine several testing rake tasks into one test run. This means that you don't have to instantiate a new rails instance (or grab the one from spring) for each test task. The time savings is considerable. This new approach removes the benefit that the `minitest` rake tasks added.

Because of these two improvements, minitest-rails dropped support for the `minitest` rake tasks and `MiniTest::Rails::Testing.default_tasks`. The proper way to specify new rake tasks is to add the following to your `Rakefile` or a file in `lib/tasks`:

```ruby
Rails::TestTask.new("test:factories" => "test:prepare") do |t|
  t.pattern = "test/factories/**/*_test.rb"
end
```
 If you want those tests run in the default task then you can also add the following to do this:

```ruby
Rake::Task["test:run"].enhance ["test:factories"]
```

However, if you don't want them run by default, then don't add that. You can always run them with the default tasks by specifying it in your rake command:

```
$ rake test test:factories
```

The rake task will add the files to the one test run. Even if you specify a test several times, it will only be run once. This is the way you add additional test directories in vanilla rails, so minitest-rails isn't adding any new functionality here. This approach works with and without minitest-rails.

## Running tests in order

> How can I test `factories` first?
> 
> Incidentally, how can I test `features` last?

Minitest 5.3.4 fixed a bug in how tests are randomized. Now test methods _and_ classes are run in random order. This ensures that you don't have any dependencies between tests. (The "unit" in "unit test" means that the test is self contained, and running in random order helps ensure that.) Because of this there is no way to specify that certain tests are run before or after other tests. The only way to do this is to run multiple groups of tests. Running `factories` last:

```
$ rake test
$ rake test:factories
```

Running `factories` first:

```
$ rake test:factories
$ rake test
```

The tradeoff being that you are instantiating a new rails instance for each test run to specify what order they are run with.

## But how can I automate this?

The cleanest way to run multiple test tasks without running multiple commands is to create a script that will do this for you.

```
$ echo "#!/usr/bin/env sh" >> ./bin/build
$ echo "" >> ./bin/build
$ echo "rake test" >> ./bin/build
$ echo "rake test:factories" >> ./bin/build
$ chmod 755 ./bin/build 
$ ./bin/build
```

**Comment by zenspider** [comment]
> On Feb 23, 2015, at 07:18, blowmage <notifications@github.com> wrote:
> 
> Rake::Task["test:run"].enhance ["test:factories"]

is the same as:

task "test:run" => "test:factories"

(which is clearer imo)

**Comment by abatko** [comment]
@blowmage - Thanks A LOT for your comprehensive reply!!

@metaskills - Thanks for the link to your blog post.
