### ISSUE TITLE
test run twice rails5

### ISSUE THREAD

**Issue by elfassy** [blowmage/minitest-rails#185]
When I have `require "minitest/rails"` in my test_helper.rb, tests run twice (`rake test`).
If I remove that require, it runs once, but `Minitest.after_run` no longer works.
Thoughts?

Rails5, Ruby 2.2.2

**Comment by elfassy** [comment]
Example app here: https://github.com/elfassy/minitest_reporter_rails5

**Comment by zenspider** [comment]
Can you start by turning off autorequire on the gemfile?

**Comment by metaskills** [comment]
I've seen this before in minitest-spec-rails. In some misc configurations with Rails 3 (MT v4.7) and Rails 4 (MT 5.x). I can not remember the specifics, but it has happened and I do remember ever find out out why.

**Comment by blowmage** [comment]
Thank you for the issue report, and extra thanks for creating a repo to recreate the errors!

The issue here is that rails5 adds its own test runner. So if you load Minitest's runner by calling `require "minitest/autorun"`, either directly or indirectly, then it will both will run tests. I would consider this a bug in rails5, and I'll spend some time looking at fixing this in raise as I assume it is likely that folks will want to use Minitest's runner, or at least features of it like `after_run`.

You can recreate this without using `minitest-rails` by changing your test helper to the following:

```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'minitest/autorun'
require "minitest/reporters"
Minitest::Reporters.use!

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

You can still use minitest-rails and not have tests run twice by setting the `MT_RAILS_NO_AUTORUN` environment variable:

```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
ENV["MT_RAILS_NO_AUTORUN"] = "true"
require 'minitest/rails'
require "minitest/reporters"
Minitest::Reporters.use!

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

Please not that the `rails5` branch in `minitest-rails` will be changing much as we get closer to a release. :)

**Comment by elfassy** [comment]
thanks for the detailed answer @blowmage!

**Comment by rpearce** [comment]
Running in to this myself with a Rails 5 (beta) app. To back up what @blowmage said, it looks like `require rails/test_help` triggers this [line of code](https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/railties/lib/rails/test_help.rb#L12) to be run, requiring [this file](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/autorun.rb) which calls `MiniTest.autorun`.

Apart from the solution above, are there currently any plans for updating `minitest-rails` to accommodate this?

**Comment by blowmage** [comment]
Rails 5 is a moving target. We will have a version of minitest-rails by the time rails 5 is released.

**Comment by williamweckl** [comment]
+1

Solved using the below code instead requiring autorun. 
```ruby
require "minitest"
require "minitest/spec"
require "minitest/mock"
require "minitest/hell" if ENV["MT_HELL"]
```

**Comment by blowmage** [comment]
Be sure to use minitest-rails 3.0.0.rc1 or higher when running on Rails 5.
