### ISSUE TITLE
Routing issue with 3.0.0.rc1

### ISSUE THREAD

**Issue by billhorsman** [blowmage/minitest-rails#193]
Hi Mike,

Excited to see this RC :)

I upgraded to minitest-rails 3.0.0.rc1 and started to get this problem in my tests on my Rails 5 app:

```
Error:
WelcomeController#test_0001_shows index:
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80index
    test/controllers/welcome_controller_test.rb:6:in `block (2 levels) in <top (required)>'
```

You can see it's trying to use a URI like `http://www.example.com:80index`.

I've reproduced this in a very simple Rails 5 app that just has one route: [Minty Test 5](https://github.com/billhorsman/minty-test-5).

I have been previously using the latest from your rails5 branch. For some reason, until very recently, the latest from that branch has been giving me a commit from [Dec 4, 2014](https://github.com/blowmage/minitest-rails/commit/acea177b38d78d723a1ff236b8b013410c3ca3be).

Bill

**Comment by blowmage** [comment]
Hey Bill, apologies of the confusion, this is intentional and I'm working on updated docs now. The big change in Rails 5 tests, and in mintiest-rails, is that ActionController::TestCase is deprecated. The 5.0 generators now generate tests that inherit from ActiveDispatch::IntegrationTest instead of AC::TC. The ActionController::TestCase class is still present in 5.0, but it will be removed in 5.1.

The issue we have is how to deal with the spec DSL when describing a Controller. When you say `describe WelcomeController` does that give you an ActionController::TestCase or an ActiveDispatch::IntegrationTest? If AD::IT then we force folks to upgrade their tests when switching to 5.0. If AC::TC then Rails 5.0 and 5.1 tests will behave differently.

I felt it was better to make the switch at a major rails release than a minor rails release, so that is why `describe <Controller>` will return an ActiveDispatch::IntegrationTest, matching the behavior of the generators.

If you want to still use ActionController::TestCase you can switch from the DSL describe to a class definition. (`class WelcomeControllerTest < ActionController::TestCase`)

**Comment by blowmage** [comment]
One idea I had was to have mintiest-rails and make `describe <Controller>` resolve to ActionController::TestCase based on whether it could detect that the rails-controller-testing gem was present. That might be a good middle ground if folks really, really want their old controller tests to work unmodified.

Let me know if this is something you would like to see and I'll do what I can to get something implemented by the time rails 5.0 and mintiest-rails 3.0 are released.

**Comment by billhorsman** [comment]
That's useful info, Mike. I took another look at [A Guide to Testing Rails Applications](http://edgeguides.rubyonrails.org/testing.html) (edge) and it makes sense to me.

Detecting the `rails-controller-testing` gem sounds like an excellent compromise. Either that, or a `minitest-rails-controller-testing` gem that people can explicitly use. It's nice to have a stepping stone on your way to a major upgrade. I have at least one app where this would be very useful. Can I help?

I've updated [Minty Test 5](https://github.com/billhorsman/minty-test-5) to do it the new way.

**Comment by blowmage** [comment]
I don't think a separate minitest-rails-* gem is the way to go. That would mean introducing a plugin mechanism. I think it would be simpler to just detect the rails-controller-testing gem. Then users only add one gem to change the behavior.

**Comment by blowmage** [comment]
@billhorsman Can you add some input on #194?
